name: General checks

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

jobs:
  check-code:
    uses: Lightning-AI/utilities/.github/workflows/check-code.yml@main
    with:
      actions-ref: main
      extra-typing: typing

  check-schema:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      azure-dir: ".azure"

  check-package:
    uses: Lightning-AI/utilities/.github/workflows/check-package.yml@main
    with:
      actions-ref: main
      import-name: "lightning_habana"
      install-extras: "[pytorch-lightning]"
      artifact-name: dist-packages-${{ github.sha }}
      testing-matrix: |
        {
          "os": ["ubuntu-latest"],
          "python-version": ["3.9"]
        }

  check-docs:
    uses: Lightning-AI/utilities/.github/workflows/check-docs.yml@main
    with:
      requirements-file: "requirements/_docs.txt"
