name: Docker

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]
    types: [opened, reopened, ready_for_review, synchronize]  # added `ready_for_review` since draft is skipped
    paths:
      - ".github/workflows/ci-dockers.yml"
      - "dockers/**"
      - "_requirements/*.txt"
      - "setup.py"
      - "!*.md"
      - "!**/*.md"
  schedule:
    - cron: "0 0 * * *"  # at the end of every day
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ ! (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')) }}

env:
  PUSH_NIGHTLY: ${{ github.event_name == 'schedule' }}

jobs:

  build-ci:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # the config used in 'dockers/ci-runner-hpu/Dockerfile'
          - {gaudi_version: "1.5.0", pytorch_version: "1.11.0"}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: env.PUSH_NIGHTLY == 'true'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          build-args: |
            DIST=latest
            GAUDI_VERSION=${{ matrix.gaudi_version }}
            PYTORCH_INSTALLER_VERSION=${{ matrix.pytorch_version }}
          file: dockers/ci-runner-hpu/Dockerfile
          push: ${{ env.PUSH_NIGHTLY }}
          tags: pytorchlightning/pytorch_lightning:hpu-ci-runner-gaudi${{ matrix.gaudi_version }}
        timeout-minutes: 10
